SELECT FK_EMP, DATA, TIPO_TURNO, FK_TIPO_POSTO_ORIGEM 
FROM WFM.CORE_ALGORITHM_SCHEDULE 
WHERE FK_EMP IN (SELECT MATRICULA FROM WFM.ESC_COLABORADOR WHERE CODIGO IN (:colabs) )
AND DATA BETWEEN to_date(:i,'yyyy-mm-dd') AND to_date(:f,'yyyy-mm-dd')
