SELECT DATA,
MEDIATURNO,
    MAXTURNO,
    MINTURNO,
    SDTURNO,
    TURNO,
    FK_TIPO_POSTO,
    DATA_TURNO
FROM WFM.CORE_ALG_TURNOS
WHERE FK_TIPO_POSTO = :p
AND DATA BETWEEN to_date(:i,'yyyy-mm-dd') AND to_date(:f,'yyyy-mm-dd')
